In [1]:
%matplotlib inline
# Dependencies and Setup
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt

In [2]:
# File to Load 
file_to_load = "Resources/fire_Final.csv"

# Read Purchasing File and store into Pandas data frame
fire_data = pd.read_csv(file_to_load)

fire_data.head()

,OBJECTID,STAT_CAUSE_DESCR,STATE,Date_Discovery,Date_Contained,FIRE_YEAR,FIRE_SIZE,LATITUDE,LONGITUDE,Duration
0,1,Miscellaneous,CA,2/2/2005,2/2/2005,2005,0.10,40.036944,-121.005833,0
1,2,Lightning,CA,5/12/2004,5/12/2004,2004,0.25,38.933056,-120.404444,0
2,3,Debris Burning,CA,5/31/2004,5/31/2004,2004,0.10,38.984167,-120.735556,0
3,4,Lightning,CA,6/28/2004,7/3/2004,2004,0.10,38.559167,-119.913333,5
4,5,Lightning,CA,6/28/2004,7/3/2004,2004,0.10,38.559167,-119.933056,5

In [3]:
#Select only 2005
fire_2005 = fire_data[fire_data.FIRE_YEAR == 2005]
#group by State
state_2005 = fire_2005.groupby(["STATE"])
#calculate total Fire_zize per state
state_fire_size_2005 = state_2005["FIRE_SIZE"].sum()
#format and write to a new csv
state_fire_size_2005_df = pd.DataFrame(state_fire_size_2005)
state_fire_size_2005_df.style.format({"FIRE_SIZE":'{:,.2f}'})
state_fire_size_2005_df.rename(columns={'FIRE_SIZE':'FIRE_SIZE_2005'}, inplace=True)
state_fire_size_2005_df.to_csv("RESOURCES/fire_size_2005.csv")
state_fire_size_2005_df.head(20)

       FIRE_SIZE_2005
STATE
AK         4482467.95
AL           43133.97
AR            9726.69
AZ          824178.29
CA          195986.22
CO           28066.88
DC               0.20
DE             160.00
FL           11804.87
GA             292.87
HI               5.40
IA            6232.70
ID          611617.93
IL             743.65
IN             421.90
KS           19752.80
KY            8199.25
LA           29583.70
MA             802.10
MD            2300.00

In [59]:
#Select only 2002
fire_2002 = fire_data[fire_data.FIRE_YEAR == 2002]
#group by State
state_2002 = fire_2002.groupby(["STATE"])
#calculate total Fire_zize per state
state_fire_size_2002 = state_2002["FIRE_SIZE"].sum()
#format and write to a new csv
state_fire_size_2002_df = pd.DataFrame(state_fire_size_2002)
state_fire_size_2002_df.style.format({"FIRE_SIZE":'{:,.2f}'})
state_fire_size_2002_df.rename(columns={'FIRE_SIZE':'FIRE_SIZE_2002'}, inplace=True)
state_fire_size_2002_df.to_csv("RESOURCES/fire_size_2002.csv")
state_fire_size_2002_df.head(15)

       FIRE_SIZE_2002
STATE
AK         1877128.10
AL            3313.40
AR            1888.20
AZ          594043.20
CA          449004.60
CO          402335.05
CT               0.30
DC               1.00
DE            1250.00
FL            4495.90
GA          160957.42
HI            3906.60
IA             226.60
ID           84723.10
IL              94.80

In [5]:
#Select only 2011
fire_2011 = fire_data[fire_data.FIRE_YEAR == 2011]
#group by State
state_2011 = fire_2011.groupby(["STATE"])
#calculate total Fire_zize per state
state_fire_size_2011 = state_2011["FIRE_SIZE"].sum()
#format and write to a new csv
state_fire_size_2011_df = pd.DataFrame(state_fire_size_2011)
state_fire_size_2011_df.style.format({"FIRE_SIZE":'{:,.2f}'})
state_fire_size_2011_df.rename(columns={'FIRE_SIZE':'FIRE_SIZE_2011'}, inplace=True)
state_fire_size_2011_df.to_csv("RESOURCES/fire_size_2011.csv")
state_fire_size_2011_df.head(10)

       FIRE_SIZE_2011
STATE
AK          227053.70
AL           53811.08
AR           46970.57
AZ         1036924.31
CA          155063.02
CO          113909.57
CT             237.38
DC               0.20
FL          328720.30
GA          437883.89

In [6]:
state_acres_df = pd.read_csv("RESOURCES/states_acres.csv")

In [44]:
#Import the  acres per state data
state_acres_df = pd.read_csv("RESOURCES/states_acres.csv")

#replace object to float do Totat Acres
state_acres_df['Total acres'] = state_acres_df['Total acres'].apply(lambda x: float(x.split()[0].replace(',', '')))
state_acres_df['Total acres'] = state_acres_df['Total acres'].astype(float)

# Combine the data into a single dataset

state_fire_size_3ya_df = pd.merge(state_acres_df, state_fire_size_2002_df, how="left", on="STATE")
state_fire_size_3yb_df = pd.merge(state_fire_size_3ya_df, state_fire_size_2005_df, how="left", on="STATE")
state_fire_size_3yc_df = pd.merge(state_fire_size_3yb_df, state_fire_size_2011_df, how="left", on="STATE")

state_fire_size_3y_df = state_fire_size_3yc_df.dropna(how="any")

state_fire_size_3y_df.style.format({"FIRE_SIZE_2011":'{:,.2f}'})
state_fire_size_3y_df.style.format({"FIRE_SIZE_2005":'{:,.2f}'})
state_fire_size_3y_df.style.format({"FIRE_SIZE_2002":'{:,.2f}'})

#print(state_fire_size_3y_df.dtypes)
state_fire_size_3y_df.head(50)

   STATE  Total acres  FIRE_SIZE_2002  FIRE_SIZE_2005  FIRE_SIZE_2011
0     AK  424491046.0    1.877128e+06      4482467.95    2.270537e+05
1     AL   33548173.0    3.313400e+03        43133.97    5.381108e+04
2     AR   34034317.0    1.888200e+03         9726.69    4.697057e+04
3     AZ   72958912.0    5.940432e+05       824178.29    1.036924e+06
4     CA  104765165.0    4.490046e+05       195986.22    1.550630e+05
5     CO   66619885.0    4.023350e+05        28066.88    1.139096e+05
7     DC      43766.0    1.000000e+00            0.20    2.000000e-01
9     FL   42082938.0    4.495900e+03        11804.87    3.287203e+05
10    GA   38031853.0    1.609574e+05          292.87    4.378839e+05
11    HI    6995827.0    3.906600e+03            5.40    2.554200e+03
12    IA   36013792.0    2.266000e+02         6232.70    7.461433e+03
13    ID   53484851.0    8.472310e+04       611617.93    3.361864e+05
14    IL   37065203.0    9.480000e+01          743.65    2.203430e+03
15    IN   23307347.0    6.472000e+02          421.90    6.995000e+02
16    KS   52657178.0    5.101210e+04        19752.80    8.201011e+04
17    KY   25861773.0    2.585670e+04         8199.25    2.379313e+04
18    LA   33177408.0    2.178400e+03        29583.70    3.545971e+04
20    MD    7940275.0    1.081000e+02         2300.00    1.018528e+04
21    ME   22646176.0    7.774800e+02            3.00    1.675800e+02
22    MI   61898310.0    9.673000e+02          311.92    1.830380e+03
23    MN   55640877.0    3.171850e+04         7162.18    1.099559e+05
24    MO   44610758.0    3.817700e+03        16445.41    3.184455e+04
25    MS   30995322.0    2.490200e+03        11705.50    9.588640e+03
26    MT   94107136.0    1.096360e+05       102299.24    1.392086e+05
27    NC   34443846.0    5.521000e+03         1477.65    1.094059e+05
28    ND   45247866.0    5.264600e+04        12869.60    2.494480e+03
29    NE   49506387.0    1.009056e+04         6362.12    3.905543e+04
30    NH    5983962.0    5.700000e+00            0.50    3.200000e+00
31    NJ    5581632.0    1.000000e-01           41.50    1.492500e+02
32    NM   77817267.0    1.449946e+05       116410.30    1.128341e+06
33    NV   70758861.0    5.223590e+04      1080035.75    4.229528e+05
34    NY   34915840.0    1.904770e+03         4959.57    1.370360e+03
35    OH   28687936.0    1.431000e+02          852.40    2.877400e+02
36    OK   44734842.0    3.340140e+04       251349.45    3.271579e+05
37    OR   62963610.0    1.010784e+06       121463.67    2.239234e+05
38    PA   29475354.0    2.920164e+03           11.90    5.794100e+02
39    PR    2191820.0    5.500000e+01         2328.40    1.190300e+03
41    SC   20492928.0    4.824100e+03          510.27    2.965605e+04
42    SD   49354554.0    8.168210e+04        13405.74    3.491882e+04
43    TN   26971693.0    2.352500e+03        24182.10    1.417980e+04
44    TX  171891725.0    1.575740e+04        53522.65    2.935501e+06
45    UT   54335251.0    2.390761e+05       235748.31    6.124171e+04
46    VA   27375488.0    1.243200e+04          444.65    1.473628e+04
48    WA   45631770.0    8.454197e+04       101243.12    3.861285e+04
49    WI   41918605.0    4.714000e+02         1012.00    6.314870e+02
50    WV   15507046.0    1.080240e+04        15394.30    5.811460e+03
51    WY   62600678.0    1.291355e+05        25936.80    9.821638e+04

In [63]:
state_percent_2002 = (state_fire_size_3y_df["FIRE_SIZE_2002"]/ state_fire_size_3y_df["Total acres"])*100
state_percent_2005 = (state_fire_size_3y_df["FIRE_SIZE_2005"]/ state_fire_size_3y_df["Total acres"])*100
state_percent_2011 = (state_fire_size_3y_df["FIRE_SIZE_2011"]/ state_fire_size_3y_df["Total acres"])*100



total_fire_3y_n = pd.concat([state_fire_size_3y_df, state_percent_2002.rename("Percent 2002"), state_percent_2005.rename("Percent 2005"), state_percent_2011.rename("Percent 2011")],  axis = 1)

#format_dict = {'Percent 2002': '{:.2%}', 'Percent 2005': '{:.2%}', 'Percent 2011': '{:.2%}'}
#total_fire_3y_n.style.format(format_dict).hide_index()

#total_fire_3y_n.sort_values(["Total acres"], ascending = False).style.format({"Percent 2002":"{:.2%}"})

#print(total_fire_3y_n.dtypes)
total_fire_3y_n.style.format({"FIRE_SIZE_2011":'{:,.2%}'})
total_fire_3y_n.style.format({"FIRE_SIZE_2005":'{:,.2%}'})
total_fire_3y_n.style.format({"FIRE_SIZE_2002":'{:,.2%}'})
total_fire_3y_n

,STATE,Total acres,FIRE_SIZE_2002,FIRE_SIZE_2005,FIRE_SIZE_2011,Percent 2002,Percent 2005,Percent 2011
0,AK,424491046.0,1.877128e+06,4482467.95,2.270537e+05,0.442207,1.055963,0.053488
1,AL,33548173.0,3.313400e+03,43133.97,5.381108e+04,0.009877,0.128573,0.160399
2,AR,34034317.0,1.888200e+03,9726.69,4.697057e+04,0.005548,0.028579,0.138009
3,AZ,72958912.0,5.940432e+05,824178.29,1.036924e+06,0.814216,1.129647,1.421244
4,CA,104765165.0,4.490046e+05,195986.22,1.550630e+05,0.428582,0.187072,0.148010
5,CO,66619885.0,4.023350e+05,28066.88,1.139096e+05,0.603926,0.042130,0.170984
7,DC,43766.0,1.000000e+00,0.20,2.000000e-01,0.002285,0.000457,0.000457
9,FL,42082938.0,4.495900e+03,11804.87,3.287203e+05,0.010683,0.028051,0.781125
10,GA,38031853.0,1.609574e+05,292.87,4.378839e+05,0.423217,0.000770,1.151361
11,HI,6995827.0,3.906600e+03,5.40,2.554200e+03,0.055842,0.000077,0.036510
12,IA,36013792.0,2.266000e+02,6232.70,7.461433e+03,0.000629,0.017306,0.020718
13,ID,53484851.0,8.472310e+04,611617.93,3.361864e+05,0.158406,1.143535,0.628564
14,IL,37065203.0,9.480000e+01,743.65,2.203430e+03,0.000256,0.002006,0.005945
15,IN,23307347.0,6.472000e+02,421.90,6.995000e+02,0.002777,0.001810,0.003001
16,KS,52657178.0,5.101210e+04,19752.80,8.201011e+04,0.096876,0.037512,0.155743
17,KY,25861773.0,2.585670e+04,8199.25,2.379313e+04,0.099980,0.031704,0.092001
18,LA,33177408.0,2.178400e+03,29583.70,3.545971e+04,0.006566,0.089168,0.106879
20,MD,7940275.0,1.081000e+02,2300.00,1.018528e+04,0.001361,0.028966,0.128274
21,ME,22646176.0,7.774800e+02,3.00,1.675800e+02,0.003433,0.000013,0.000740
22,MI,61898310.0,9.673000e+02,311.92,1.830380e+03,0.001563,0.000504,0.002957
23,MN,55640877.0,3.171850e+04,7162.18,1.099559e+05,0.057006,0.012872,0.197617
24,MO,44610758.0,3.817700e+03,16445.41,3.184455e+04,0.008558,0.036864,0.071383
25,MS,30995322.0,2.490200e+03,11705.50,9.588640e+03,0.008034,0.037765,0.030936
26,MT,94107136.0,1.096360e+05,102299.24,1.392086e+05,0.116501,0.108705,0.147926
27,NC,34443846.0,5.521000e+03,1477.65,1.094059e+05,0.016029,0.004290,0.317635
28,ND,45247866.0,5.264600e+04,12869.60,2.494480e+03,0.116350,0.028442,0.005513
29,NE,49506387.0,1.009056e+04,6362.12,3.905543e+04,0.020382,0.012851,0.078890
30,NH,5983962.0,5.700000e+00,0.50,3.200000e+00,0.000095,0.000008,0.000053
31,NJ,5581632.0,1.000000e-01,41.50,1.492500e+02,0.000002,0.000744,0.002674
32,NM,77817267.0,1.449946e+05,116410.30,1.128341e+06,0.186327,0.149594,1.449988
33,NV,70758861.0,5.223590e+04,1080035.75,4.229528e+05,0.073822,1.526361,0.597738
34,NY,34915840.0,1.904770e+03,4959.57,1.370360e+03,0.005455,0.014204,0.003925
35,OH,28687936.0,1.431000e+02,852.40,2.877400e+02,0.000499,0.002971,0.001003
36,OK,44734842.0,3.340140e+04,251349.45,3.271579e+05,0.074665,0.561865,0.731327
37,OR,62963610.0,1.010784e+06,121463.67,2.239234e+05,1.605347,0.192911,0.355639
38,PA,29475354.0,2.920164e+03,11.90,5.794100e+02,0.009907,0.000040,0.001966
39,PR,2191820.0,5.500000e+01,2328.40,1.190300e+03,0.002509,0.106231,0.054306
41,SC,20492928.0,4.824100e+03,510.27,2.965605e+04,0.023540,0.002490,0.144714
42,SD,49354554.0,8.168210e+04,13405.74,3.491882e+04,0.165501,0.027162,0.070751
43,TN,26971693.0,2.352500e+03,24182.10,1.417980e+04,0.008722,0.089657,0.052573
44,TX,171891725.0,1.575740e+04,53522.65,2.935501e+06,0.009167,0.031137,1.707761
45,UT,54335251.0,2.390761e+05,235748.31,6.124171e+04,0.440002,0.433877,0.112711
46,VA,27375488.0,1.243200e+04,444.65,1.473628e+04,0.045413,0.001624,0.053830
48,WA,45631770.0,8.454197e+04,101243.12,3.861285e+04,0.185270,0.221870,0.084618
49,WI,41918605.0,4.714000e+02,1012.00,6.314870e+02,0.001125,0.002414,0.001506
50,WV,15507046.0,1.080240e+04,15394.30,5.811460e+03,0.069661,0.099273,0.037476
51,WY,62600678.0,1.291355e+05,25936.80,9.821638e+04,0.206285,0.041432,0.156893

In [61]:
total_fire_3y_n.set_index("STATE", inplace=True)
total_fire_3y_n

,Total acres,FIRE_SIZE_2002,FIRE_SIZE_2005,FIRE_SIZE_2011,Percent 2002,Percent 2005,Percent 2011
STATE,,,,,,,
AK,424491046.0,1.877128e+06,4482467.95,2.270537e+05,4.422068e-03,1.055963e-02,5.348845e-04
AL,33548173.0,3.313400e+03,43133.97,5.381108e+04,9.876544e-05,1.285732e-03,1.603994e-03
AR,34034317.0,1.888200e+03,9726.69,4.697057e+04,5.547930e-05,2.857907e-04,1.380094e-03
AZ,72958912.0,5.940432e+05,824178.29,1.036924e+06,8.142161e-03,1.129647e-02,1.421244e-02
CA,104765165.0,4.490046e+05,195986.22,1.550630e+05,4.285820e-03,1.870719e-03,1.480101e-03
CO,66619885.0,4.023350e+05,28066.88,1.139096e+05,6.039264e-03,4.212988e-04,1.709843e-03
DC,43766.0,1.000000e+00,0.20,2.000000e-01,2.284879e-05,4.569757e-06,4.569757e-06
FL,42082938.0,4.495900e+03,11804.87,3.287203e+05,1.068343e-04,2.805144e-04,7.811249e-03
GA,38031853.0,1.609574e+05,292.87,4.378839e+05,4.232174e-03,7.700650e-06,1.151361e-02
HI,6995827.0,3.906600e+03,5.40,2.554200e+03,5.584186e-04,7.718887e-07,3.651034e-04
IA,36013792.0,2.266000e+02,6232.70,7.461433e+03,6.292034e-06,1.730643e-04,2.071826e-04
ID,53484851.0,8.472310e+04,611617.93,3.361864e+05,1.584058e-03,1.143535e-02,6.285638e-03
IL,37065203.0,9.480000e+01,743.65,2.203430e+03,2.557655e-06,2.006329e-05,5.944740e-05
IN,23307347.0,6.472000e+02,421.90,6.995000e+02,2.776807e-05,1.810159e-05,3.001200e-05
KS,52657178.0,5.101210e+04,19752.80,8.201011e+04,9.687587e-04,3.751207e-04,1.557435e-03
KY,25861773.0,2.585670e+04,8199.25,2.379313e+04,9.998038e-04,3.170413e-04,9.200116e-04
LA,33177408.0,2.178400e+03,29583.70,3.545971e+04,6.565914e-05,8.916821e-04,1.068791e-03
MD,7940275.0,1.081000e+02,2300.00,1.018528e+04,1.361414e-05,2.896625e-04,1.282736e-03
ME,22646176.0,7.774800e+02,3.00,1.675800e+02,3.433162e-05,1.324727e-07,7.399925e-06
MI,61898310.0,9.673000e+02,311.92,1.830380e+03,1.562724e-05,5.039233e-06,2.957076e-05
MN,55640877.0,3.171850e+04,7162.18,1.099559e+05,5.700575e-04,1.287216e-04,1.976171e-03
MO,44610758.0,3.817700e+03,16445.41,3.184455e+04,8.557801e-05,3.686422e-04,7.138312e-04
MS,30995322.0,2.490200e+03,11705.50,9.588640e+03,8.034116e-05,3.776538e-04,3.093577e-04
MT,94107136.0,1.096360e+05,102299.24,1.392086e+05,1.165013e-03,1.087051e-03,1.479256e-03
NC,34443846.0,5.521000e+03,1477.65,1.094059e+05,1.602899e-04,4.290026e-05,3.176355e-03
ND,45247866.0,5.264600e+04,12869.60,2.494480e+03,1.163502e-03,2.844245e-04,5.512923e-05
NE,49506387.0,1.009056e+04,6362.12,3.905543e+04,2.038234e-04,1.285111e-04,7.888968e-04
NH,5983962.0,5.700000e+00,0.50,3.200000e+00,9.525462e-07,8.355668e-08,5.347628e-07
NJ,5581632.0,1.000000e-01,41.50,1.492500e+02,1.791591e-08,7.435101e-06,2.673949e-05
NM,77817267.0,1.449946e+05,116410.30,1.128341e+06,1.863270e-03,1.495944e-03,1.449988e-02
NV,70758861.0,5.223590e+04,1080035.75,4.229528e+05,7.382241e-04,1.526361e-02,5.977384e-03
NY,34915840.0,1.904770e+03,4959.57,1.370360e+03,5.455318e-05,1.420436e-04,3.924752e-05
OH,28687936.0,1.431000e+02,852.40,2.877400e+02,4.988159e-06,2.971284e-05,1.003000e-05
OK,44734842.0,3.340140e+04,251349.45,3.271579e+05,7.466529e-04,5.618651e-03,7.313268e-03
OR,62963610.0,1.010784e+06,121463.67,2.239234e+05,1.605347e-02,1.929109e-03,3.556393e-03
PA,29475354.0,2.920164e+03,11.90,5.794100e+02,9.907137e-05,4.037271e-07,1.965744e-05
PR,2191820.0,5.500000e+01,2328.40,1.190300e+03,2.509330e-05,1.062314e-03,5.430647e-04
SC,20492928.0,4.824100e+03,510.27,2.965605e+04,2.354032e-04,2.489981e-05,1.447136e-03
SD,49354554.0,8.168210e+04,13405.74,3.491882e+04,1.655006e-03,2.716211e-04,7.075096e-04
TN,26971693.0,2.352500e+03,24182.10,1.417980e+04,8.722107e-05,8.965733e-04,5.257290e-04
TX,171891725.0,1.575740e+04,53522.65,2.935501e+06,9.167050e-05,3.113742e-04,1.707761e-02
UT,54335251.0,2.390761e+05,235748.31,6.124171e+04,4.400018e-03,4.338773e-03,1.127108e-03
VA,27375488.0,1.243200e+04,444.65,1.473628e+04,4.541289e-04,1.624263e-05,5.383020e-04
WA,45631770.0,8.454197e+04,101243.12,3.861285e+04,1.852700e-03,2.218698e-03,8.461835e-04
WI,41918605.0,4.714000e+02,1012.00,6.314870e+02,1.124560e-05,2.414202e-05,1.506460e-05
WV,15507046.0,1.080240e+04,15394.30,5.811460e+03,6.966124e-04,9.927294e-04,3.747625e-04
WY,62600678.0,1.291355e+05,25936.80,9.821638e+04,2.062845e-03,4.143214e-04,1.568935e-03

In [62]:
fire_size_percentage_CA_GA = total_fire_3y_n.loc[["CA", "GA"]]
fire_size_percentage_CA_GA

,Total acres,FIRE_SIZE_2002,FIRE_SIZE_2005,FIRE_SIZE_2011,Percent 2002,Percent 2005,Percent 2011
STATE,,,,,,,
CA,104765165.0,449004.60,195986.22,155063.02,0.004286,0.001871,0.001480
GA,38031853.0,160957.42,292.87,437883.89,0.004232,0.000008,0.011514