In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
fire_csv = "Fire_Program_Analysis__Fire_Occurrence_Database_Feature_Layer.csv"

df_fire = pd.read_csv(fire_csv, low_memory=False)

df_fire.head(10)

,X,Y,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,...,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME
0,-123.655847,41.211394,1001,1013,FS-1421079,FED,FS-FIRESTAT,FS,USCASRF,Six Rivers National Forest,...,0.1,A,41.211389,-123.655833,5,USFS,CA,NaN,NaN,NaN
1,-118.619736,44.841672,1002,1014,FS-1421080,FED,FS-FIRESTAT,FS,USORUMF,Umatilla National Forest,...,0.5,B,44.841667,-118.619722,5,USFS,OR,23,23.0,Grant
2,-118.513625,44.984450,1003,1015,FS-1421083,FED,FS-FIRESTAT,FS,USORUMF,Umatilla National Forest,...,0.1,A,44.984444,-118.513611,5,USFS,OR,23,23.0,Grant
3,-105.651954,35.751395,1004,1016,FS-1421088,FED,FS-FIRESTAT,FS,USNMSNF,Santa Fe National Forest,...,1.5,B,35.751389,-105.651944,5,USFS,NM,47,47.0,San Miguel
4,-111.395567,39.938062,1005,1017,FS-1421090,FED,FS-FIRESTAT,FS,USUTMLF,Manti-Lasal National Forest,...,1.5,B,39.938056,-111.395556,5,USFS,UT,49,49.0,Utah
5,-93.199729,30.938894,1006,1018,FS-1421093,FED,FS-FIRESTAT,FS,USLAKIF,Kisatchie National Forest,...,1.0,B,30.938889,-93.199722,5,USFS,LA,NaN,NaN,NaN
6,-92.764451,31.258894,1007,1019,FS-1421095,FED,FS-FIRESTAT,FS,USLAKIF,Kisatchie National Forest,...,1.0,B,31.258889,-92.764444,5,USFS,LA,NaN,NaN,NaN
7,-92.511673,31.631950,1008,1020,FS-1421098,FED,FS-FIRESTAT,FS,USLAKIF,Kisatchie National Forest,...,1.0,B,31.631944,-92.511667,5,USFS,LA,NaN,NaN,NaN
8,-92.958340,31.066672,1009,1021,FS-1421100,FED,FS-FIRESTAT,FS,USLAKIF,Kisatchie National Forest,...,15.0,C,31.066667,-92.958333,5,USFS,LA,NaN,NaN,NaN
9,-101.636953,37.088062,1010,1022,FS-1421101,FED,FS-FIRESTAT,FS,USKSPSF,Pike San Isabel National Forest and Grasslands,...,0.5,B,37.088056,-101.636944,5,USFS,KS,NaN,NaN,NaN

In [5]:
df_fire.count()

X                             1880465
Y                             1880465
OBJECTID                      1880465
FOD_ID                        1880465
FPA_ID                        1880465
SOURCE_SYSTEM_TYPE            1880465
SOURCE_SYSTEM                 1880465
NWCG_REPORTING_AGENCY         1880465
NWCG_REPORTING_UNIT_ID        1880465
NWCG_REPORTING_UNIT_NAME      1880465
SOURCE_REPORTING_UNIT         1880465
SOURCE_REPORTING_UNIT_NAME    1880465
LOCAL_FIRE_REPORT_ID           421179
LOCAL_INCIDENT_ID             1059644
FIRE_CODE                      324724
FIRE_NAME                      919986
ICS_209_INCIDENT_NUMBER         25717
ICS_209_NAME                    25717
MTBS_ID                         11003
MTBS_FIRE_NAME                  11003
COMPLEX_NAME                     5183
FIRE_YEAR                     1880465
DISCOVERY_DATE                1880465
DISCOVERY_DOY                 1880465
DISCOVERY_TIME                 997827
STAT_CAUSE_CODE               1880465
STAT_CAUSE_DESCR              1880465
CONT_DATE                      988934
CONT_DOY                       988934
CONT_TIME                      907912
FIRE_SIZE                     1880465
FIRE_SIZE_CLASS               1880465
LATITUDE                      1880465
LONGITUDE                     1880465
OWNER_CODE                    1880465
OWNER_DESCR                   1880465
STATE                         1880465
COUNTY                        1202317
FIPS_CODE                     1202317
FIPS_NAME                     1202317
dtype: int64

In [11]:
df_fire.columns

Index(['X', 'Y', 'OBJECTID', 'FOD_ID', 'FPA_ID', 'SOURCE_SYSTEM_TYPE',
       'SOURCE_SYSTEM', 'NWCG_REPORTING_AGENCY', 'NWCG_REPORTING_UNIT_ID',
       'NWCG_REPORTING_UNIT_NAME', 'SOURCE_REPORTING_UNIT',
       'SOURCE_REPORTING_UNIT_NAME', 'LOCAL_FIRE_REPORT_ID',
       'LOCAL_INCIDENT_ID', 'FIRE_CODE', 'FIRE_NAME',
       'ICS_209_INCIDENT_NUMBER', 'ICS_209_NAME', 'MTBS_ID', 'MTBS_FIRE_NAME',
       'COMPLEX_NAME', 'FIRE_YEAR', 'DISCOVERY_DATE', 'DISCOVERY_DOY',
       'DISCOVERY_TIME', 'STAT_CAUSE_CODE', 'STAT_CAUSE_DESCR', 'CONT_DATE',
       'CONT_DOY', 'CONT_TIME', 'FIRE_SIZE', 'FIRE_SIZE_CLASS', 'LATITUDE',
       'LONGITUDE', 'OWNER_CODE', 'OWNER_DESCR', 'STATE', 'COUNTY',
       'FIPS_CODE', 'FIPS_NAME'],
      dtype='object')

In [16]:
df_sub = df_fire[['OBJECTID', 'STAT_CAUSE_DESCR', 'STATE', 'CONT_DATE', 'DISCOVERY_DATE', 'FIRE_SIZE', 'LATITUDE', 'LONGITUDE']]
df_sub.head()

,OBJECTID,STAT_CAUSE_DESCR,STATE,CONT_DATE,DISCOVERY_DATE,FIRE_SIZE,LATITUDE,LONGITUDE
0,1001,Miscellaneous,CA,2005-03-17T00:00:00.000Z,2005-03-17T00:00:00.000Z,0.1,41.211389,-123.655833
1,1002,Lightning,OR,2005-07-31T00:00:00.000Z,2005-07-31T00:00:00.000Z,0.5,44.841667,-118.619722
2,1003,Campfire,OR,2005-07-31T00:00:00.000Z,2005-07-31T00:00:00.000Z,0.1,44.984444,-118.513611
3,1004,Miscellaneous,NM,2005-08-02T00:00:00.000Z,2005-07-31T00:00:00.000Z,1.5,35.751389,-105.651944
4,1005,Lightning,UT,2005-06-30T00:00:00.000Z,2005-06-15T00:00:00.000Z,1.5,39.938056,-111.395556

In [18]:
df_sub.to_csv("fire.csv")

In [19]:
df_sub.to_csv("fire.txt")

In [20]:
df_dropna = df_sub.dropna(how="any")

In [21]:
df_dropna.count()

OBJECTID            988934
STAT_CAUSE_DESCR    988934
STATE               988934
CONT_DATE           988934
DISCOVERY_DATE      988934
FIRE_SIZE           988934
LATITUDE            988934
LONGITUDE           988934
dtype: int64

In [22]:
df_dropna["OBJECTID"].nunique()

988934

In [23]:
df_clean = df_dropna.rename(columns={"OBJECTID": "Fire_ID", "STAT_CAUSE_DESCR": "Cause", "STATE": "State", "CONT_DATE": "Date_Contained", "DISCOVERY_DATE": "Discovery_Date", "FIRE_SIZE": "Fire_Size"})

In [24]:
df_clean.head()

,Fire_ID,Cause,State,Date_Contained,Discovery_Date,Fire_Size,LATITUDE,LONGITUDE
0,1001,Miscellaneous,CA,2005-03-17T00:00:00.000Z,2005-03-17T00:00:00.000Z,0.1,41.211389,-123.655833
1,1002,Lightning,OR,2005-07-31T00:00:00.000Z,2005-07-31T00:00:00.000Z,0.5,44.841667,-118.619722
2,1003,Campfire,OR,2005-07-31T00:00:00.000Z,2005-07-31T00:00:00.000Z,0.1,44.984444,-118.513611
3,1004,Miscellaneous,NM,2005-08-02T00:00:00.000Z,2005-07-31T00:00:00.000Z,1.5,35.751389,-105.651944
4,1005,Lightning,UT,2005-06-30T00:00:00.000Z,2005-06-15T00:00:00.000Z,1.5,39.938056,-111.395556